### ISSUE TITLE
小程序源代码获取工具哪个可以用，没有app.json文件

### ISSUE THREAD

**Issue by yunmangmeng** [Angels-Ray/UnpackMiniApp#1]

**Comment by Angels-Ray** [comment]
wxapkgconvertor和wxappUnpacker都行。没有反编译成功哪来的app.json？

**Comment by yunmangmeng** [comment]
我用的wxappUnpacker（wxapk都是未加密的，），主包反编译成功了，分包一直报错，代码：https://www.123pan.com/s/I0XcVv-LeOxd.html，_1640087070_392.wxapkg是主包，有时间可以帮我看一下吗
[Uploading ASD.zip…]()

**Comment by Angels-Ray** [comment]
> 我用的wxappUnpacker（wxapk都是未加密的，），主包反编译成功了，分包一直报错，代码：[https://www.123pan.com/s/I0XcVv-LeOxd.html，_1640087070_392.wxapkg是主包，有时间可以帮我看一下吗](https://www.123pan.com/s/I0XcVv-LeOxd.html%EF%BC%8C_1640087070_392.wxapkg%E6%98%AF%E4%B8%BB%E5%8C%85%EF%BC%8C%E6%9C%89%E6%97%B6%E9%97%B4%E5%8F%AF%E4%BB%A5%E5%B8%AE%E6%88%91%E7%9C%8B%E4%B8%80%E4%B8%8B%E5%90%97) Uploading ASD.zip…

我解包后也没有app.json，缺少包或者反编译工具太旧失效了
